INSERT INTO users (name, surname, email, role, password)
VALUES ('Paul', 'Smith', 'admin', 'ADMIN', '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('John', 'Doe', 'test@gmail.com', 'USER', '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('John', 'Smith', 'jsmith321@gmail.com', 'USER', '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Michael', 'Brown', 'mbrown789@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Sarah', 'Davis', 'sdavis234@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('David', 'Wilson', 'dwilson567@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Jennifer', 'Martinez', 'jmartinez890@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Christopher', 'Taylor', 'ctaylor123@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Jessica', 'Anderson', 'janderson456@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Daniel', 'Thomas', 'dthomas789@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu'),
       ('Amanda', 'Clark', 'aclark012@gmail.com', 'USER',
        '$2a$10$SOiGoS/OEGvvJVaHsrru1.6RxA4XTppX/1zWhrU.tneaNCilPcYnu');

INSERT INTO tasks (title, description, date, status, user_id)
VALUES ('Add controller', 'Description', '2024-04-13', 'PLANNED', 1),
       ('Fix service', 'Description', '2024-04-13', 'IN_PROGRESS', 2),
       ('Do refactoring', 'Description', '2024-04-13', 'DONE', 2),
       ('Add sample data', 'Description', '2024-04-13', 'PLANNED', 4),
       ('Change button color', 'Description', '2024-04-13', 'IN_PROGRESS', 5),
       ('Add new page', 'Description', '2024-04-13', 'CANCELLED', 5),
       ('Fix bug', 'Description', '2024-04-13', 'PLANNED', 7),
       ('Add new functionality', 'Description', '2024-04-13', 'IN_PROGRESS', 8);